# Установка команды home-server в PATH (Windows).
# После установки можно вызывать home-server из любой папки.
# Использование: .\scripts\install-cli.ps1 [--uninstall]

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ROOT = Split-Path -Parent $ScriptDir
$launcherName = "home-server.ps1"
$launcherPath = Join-Path $ROOT $launcherName

# Папка в PATH: сначала пользовательская
$userPath = [Environment]::GetFolderPath("UserProfile")
$binDir = Join-Path $userPath "bin"
if (-not (Test-Path $binDir)) {
    $binDir = Join-Path $userPath ".local\bin"
}
if (-not (Test-Path $binDir)) {
    New-Item -ItemType Directory -Path $binDir -Force | Out-Null
}
$targetPath = Join-Path $binDir "home-server.ps1"

function Add-BinToPath {
    $currentPath = [Environment]::GetEnvironmentVariable("Path", "User")
    if ($currentPath -notlike "*$binDir*") {
        [Environment]::SetEnvironmentVariable("Path", "$binDir;$currentPath", "User")
        $env:Path = "$binDir;$env:Path"
        Write-Host "Добавлена в PATH пользователя: $binDir"
    }
}

if ($args -contains "--uninstall") {
    if (Test-Path $targetPath) {
        Remove-Item -Force $targetPath
        Write-Host "Команда удалена: $targetPath"
    } else {
        Write-Host "Команда не установлена в $targetPath"
    }
    exit 0
}

# Создаём launcher в корне проекта, если ещё нет
$launcherContent = @"
# Launcher for Home Server (generated by install-cli.ps1)
`$ROOT = "$ROOT"
Set-Location `$ROOT
& "`$ROOT\start.ps1" @args
"@
Set-Content -Path $launcherPath -Value $launcherContent -Encoding UTF8

# Копируем launcher в bin
Copy-Item -Path $launcherPath -Destination $targetPath -Force
Write-Host "Установлено: $targetPath"
Add-BinToPath
Write-Host ""
Write-Host "Теперь можно запускать из любой папки:"
Write-Host "  home-server.ps1"
Write-Host "Или создайте алиас/батник 'home-server' без расширения (опционально)."
Write-Host "Если команда не находится, перезапустите терминал (PATH обновлён для текущего пользователя)."
